# Generated by Django 6.0.3 on 2026-04-06 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название клиники')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Клиника',
                'verbose_name_plural': 'Клиники',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('animal_type', models.CharField(max_length=50, verbose_name='Вид (собака, кошка и т.д.)')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('owner_name', models.CharField(max_length=200, verbose_name='Владелец')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='core.clinic', verbose_name='Клиника')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата приёма')),
                ('diagnosis', models.CharField(max_length=300, verbose_name='Диагноз')),
                ('treatment', models.TextField(blank=True, verbose_name='Назначения')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.clinic', verbose_name='Клиника')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.pet', verbose_name='Животное')),
            ],
            options={
                'verbose_name': 'Визит',
                'verbose_name_plural': 'Визиты',
            },
        ),
    ]
