# Generated by Django 6.0.3 on 2026-04-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='chip_number',
            field=models.CharField(blank=True, help_text='Уникальный 15-значный номер (ISO 11784/11785)', max_length=15, null=True, unique=True, verbose_name='Номер чипа'),
        ),
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pet_photos/', verbose_name='Фото питомца'),
        ),
    ]
