# Generated by Django 6.0.3 on 2026-04-19 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pet_chip_number_pet_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('specialization', models.CharField(blank=True, max_length=100, verbose_name='Специализация')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Владелец',
                'verbose_name_plural': 'Владельцы',
            },
        ),
        migrations.RemoveField(
            model_name='pet',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=100, verbose_name='Порода'),
        ),
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Окрас'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст (лет)'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='core.clinic', verbose_name='Клиника регистрации'),
        ),
        migrations.AddField(
            model_name='visit',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='core.employee', verbose_name='Ветеринар'),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='core.owner', verbose_name='Владелец'),
        ),
    ]
