# Generated by Django 6.0.3 on 2026-05-13 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_owner_remove_pet_owner_name_pet_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='owner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='animal_type',
            field=models.CharField(max_length=50, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='chip_number',
            field=models.CharField(blank=True, help_text='ISO 11784/11785', max_length=15, null=True, unique=True, verbose_name='Номер чипа'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clinic', verbose_name='Клиника регистрации'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.owner', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pet_photos/', verbose_name='Фото'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['chip_number'], name='core_pet_chip_nu_c930e8_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['animal_type'], name='core_pet_animal__35a170_idx'),
        ),
    ]
